# .streamlit/secrets.toml

public_gsheets_url = "https://docs.google.com/spreadsheets/d/1vgBGD5UluXA8cvSw7_pW_sZXOupNCwGFXUTlrO2h8w4/edit?usp=sharing"

OPENAI_API_KEY = "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"

HUGGINGFACEHUB_API_TOKEN = "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"

[openai]
api_key = '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'
